package:
  name: divinepy
  version: 0.3.0
source:
  sha256: 40490ae968d2a8ae4cbb2ba9ddcbdc619479d855f01f21fb536c8d845635a7da
  url: https://files.pythonhosted.org/packages/70/17/47150aeccadda7b221d130638d6876b4905a6b1c6ce22f1d01035e9ca787/divinepy-0.3.0.tar.gz
about:
  dev_url: https://michaelaye.github.io
  doc_url: https://michaelaye.github.io
  home: https://michaelaye.github.io
  license: Apache Software
  license_family: APACHE
  summary: Diviner data tools
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - michaelaye
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas
  - xarray
  - rasterio
  - dask
  - hvplot
  run:
  - pip
  - python
  - packaging
  - pandas
  - xarray
  - rasterio
  - dask
  - hvplot
test:
  imports:
  - divinepy
