# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"raster_to_xarray": "00_core.ipynb",
         "mapcycle_to_xarray": "00_core.ipynb",
         "read_images_into_stacked_array": "00_core.ipynb",
         "read_mapcycles_into_stacked_array": "00_core.ipynb",
         "get_data_for_pixel": "00_core.ipynb",
         "root": "04_l3data.ipynb",
         "datasets": "01_dems.ipynb",
         "LOLA_TOPO": "01_dems.ipynb",
         "t_prime": "01a_dem_corrections.ipynb",
         "lat_prime": "01a_dem_corrections.ipynb",
         "DIVINER_URL": "04_l3data.ipynb",
         "L2DataManager": "03_l2data.ipynb",
         "get_l2_image_paths": "03_l2data.ipynb",
         "L2Data": "03_l2data.ipynb",
         "LocalTime": "03_l2data.ipynb",
         "L3DataManager": "04_l3data.ipynb",
         "get_l3_image_paths": "04_l3data.ipynb",
         "L3Data": "04_l3data.ipynb",
         "STData": "04_l3data.ipynb"}

modules = ["core.py",
           "dems.py",
           "dem_corrections.py",
           "divdata.py",
           "l2data.py",
           "l3data.py"]

doc_url = "https://michaelaye.github.io/divinepy/"

git_url = "https://github.com/michaelaye/divinepy/tree/master/"

def custom_doc_links(name): return None
