# AUTOGENERATED! DO NOT EDIT! File to edit: 06_l1a_data.ipynb (unless otherwise specified).

__all__ = ['base_url_1']

# Cell
import pandas as pd
from yarl import URL

base_url_1 = URL(
    "https://pds-geosciences.wustl.edu/lro/lro-l-dlre-2-edr-v1/lrodlr_0001/data/"
)